//
//  ListsDefaults.swift
//  Find
//
//  Created by A. Zheng (github.com/aheze) on 4/20/22.
//  Copyright © 2022 A. Zheng. All rights reserved.
//

import UIKit

extension List {
    static var defaultLists: [List] {
        var lists: [List] = [
            .init(
                title: "Milk",
                description: "Avoiding Milk",
                icon: "cup.and.saucer.fill",
                color: 0x0089CF,
                words: [
                    "Butter",
                    "Buttermilk",
                    "Casein",
                    "Casein hydrolysate",
                    "Caseinate",
                    "Cheese",
                    "Cottage cheese",
                    "Cream",
                    "Curds",
                    "Custard",
                    "Ghee",
                    "Half-and-half",
                    "Lactalbumin",
                    "Lactic acid starter culture",
                    "Lactoferrin",
                    "Lactoglobulin",
                    "Lactose",
                    "Lactulose",
                    "Milk",
                    "Milk protein hydrolysate",
                    "Pudding",
                    "Recaldent",
                    "Rennet casein",
                    "Simplesse",
                    "Sour cream",
                    "Sour milk solids",
                    "Tagatose",
                    "Whey",
                    "Whey protein hydrolysate",
                    "Yogurt",

                ],
                dateCreated: Date()
            ),
            .init(
                title: "Egg",
                description: "Avoiding Egg",
                icon: "oval.portrait",
                color: 0x02BB00,
                words: [
                    "Albumin",
                    "Albumen",
                    "Apovitellin",
                    "Avidin globulin",
                    "Egg",
                    "Eggnog",
                    "Lysozyme",
                    "Mayonnaise",
                    "Meringue",
                    "Ovalbumin",
                    "Ovomucoid",
                    "Ovomucin",
                    "Ovovitellin",
                    "Surimi",
                    "Vitellin",
                    "Yolk",

                ],
                dateCreated: Date()
            ),
            .init(
                title: "Peanut",
                description: "Avoiding Peanut",
                icon: "circle.grid.2x1",
                color: 0x8E5600,
                words: [
                    "Nut",
                    "Arachis oil",
                    "Beer nuts",
                    "Ground nuts",
                    "Lupin",
                    "Mandelona",
                    "Mixed nuts",
                    "Monkey nuts",
                    "Nut pieces",
                    "Peanut butter",
                    "Peanut flour",
                    "Peanut protein hydrolysate",

                ],
                dateCreated: Date()
            ),
            .init(
                title: "Soy",
                description: "Avoiding Soy",
                icon: "cube",
                color: 0xD12D00,
                words: [
                    "Soy",
                    "Edamame",
                    "Miso",
                    "Natto",
                    "Okara",
                    "Shoyu",
                    "Soya",
                    "Soybean",
                    "Tamari",
                    "Tempeh",
                    "Textured vegetable protein",
                    "TVP",
                    "Tofu",

                ],
                dateCreated: Date()
            ),
            .init(
                title: "Wheat",
                description: "Avoiding Wheat",
                icon: "laurel.leading",
                color: 0xCEA700,
                words: [
                    "Wheat",
                    "Bran",
                    "Bread",
                    "Bulgur",
                    "Cake",
                    "Cereal extract",
                    "Club wheat",
                    "Couscous",
                    "Cracker meal",
                    "Durum",
                    "Einkorn",
                    "Emmer",
                    "Farina",
                    "Farro",
                    "Flour",
                    "Freekeh",
                    "Germ",
                    "Graham",
                    "Hydrolyzed wheat protein",
                    "Kamut",
                    "Malt",
                    "Matzoh",
                    "Matzo",
                    "Matzah",
                    "Matza",
                    "Pasta",
                    "Seitan",
                    "Starch",
                    "Semolina",
                    "Spelt",
                    "Sprouted wheat",
                    "Triticale",
                    "Vital wheat gluten",

                ],
                dateCreated: Date()
            ),
            .init(
                title: "Tree Nuts",
                description: "Avoiding Tree Nuts",
                icon: "leaf.fill",
                color: 0x00A724,
                words: [
                    "Almond",
                    "Artificial nuts",
                    "Beechnut",
                    "Brazil nut",
                    "Butternut",
                    "Cashew",
                    "Chestnut",
                    "Chinquapin nut",
                    "Coconut",
                    "Filbert/hazelnut",
                    "Gianduja",
                    "Ginkgo",
                    "Hickory",
                    "Lichee",
                    "Lychee",
                    "Macadamia nut",
                    "Marzipan",
                    "Nangai",
                    "Pecan",
                    "Pesto",
                    "Pili nut",
                    "Pine nut",
                    "Pigñolia",
                    "Pignon",
                    "Pinyon",
                    "Pistachio",
                    "Praline",
                    "Shea",
                    "Walnut",
                ],
                dateCreated: Date()
            ),
            .init(
                title: "Shellfish",
                description: "Avoiding Shellfish",
                icon: "water.waves",
                color: 0xE60069,
                words: [
                    "Barnacle",
                    "Crab",
                    "Crawfish",
                    "Crawdad",
                    "Crayfish",
                    "Ecrevisse",
                    "Krill",
                    "Lobster",
                    "Langouste",
                    "Langoustine",
                    "Moreton bay bugs",
                    "Scampi",
                    "Tomalley",
                    "Prawns",
                    "Shrimp",
                    "Crevette",
                ],
                dateCreated: Date()
            ),
            .init(
                title: "Fish",
                description: "Avoiding Fish",
                icon: "fish",
                color: 0x0031E6,
                words: [
                    "Fish",
                    "Anchovies",
                    "Bass",
                    "Catfish",
                    "Cod",
                    "Flounder",
                    "Grouper",
                    "Haddock",
                    "Hake",
                    "Halibut",
                    "Herring",
                    "Mahi mahi",
                    "Perch",
                    "Pike",
                    "Pollock",
                    "Salmon",
                    "Scrod",
                    "Sole",
                    "Snapper",
                    "Swordfish",
                    "Tilapia",
                    "Trout",
                    "Tuna",
                ],
                dateCreated: Date()
            ),
            .init(
                title: "Sesame",
                description: "Avoiding Sesame",
                icon: "circle.dotted",
                color: 0x662700,
                words: [
                    "Sesame",
                    "Benne",
                    "Benniseed",
                    "Gingelly",
                    "Gomasio",
                    "Halvah",
                    "Sesamol",
                    "Sesamum indicum",
                    "Sesemolina",
                    "Sim sim",
                    "Tahini",
                    "Tahina",
                    "Tehina",
                    "Til",
                ],
                dateCreated: Date()
            ),
        ]

        let startingDate = Date()
        for index in lists.indices {
            let offset = Double(index) /// add 1 second into the future
            let date = startingDate.addingTimeInterval(offset)
            lists[index].dateCreated = date
        }

        return lists
    }
}

// .init(
//    title: "Beef",
//    description: "Meat from cows",
//    icon: "capsule.fill",
//    color: 0x612F00,
//    words: [
//        "Cow",
//        "Beef",
//        "Steak",
//        "Ribeye",
//        "Tenderloin",
//        "Filet Mignon",
//        "Porterhouse",
//        "T-Bone",
//        "Flank",
//        "Ribs",
//        "Bovine",
//        "Burger",
//        "Pastrami"
//    ],
//    dateCreated: Date()
// ),
// .init(
//    title: "Nuts",
//    description: "Assorted nuts",
//    icon: "capsule.portrait.fill",
//    color: 0x9E6800,
//    words: [
//        "Nut",
//        "Peanut",
//        "Macadamia",
//        "Almond",
//        "Cashew",
//        "Chestnut",
//        "Walnut",
//        "Hazelnut",
//        "Pecan",
//        "Pistachio"
//    ],
//    dateCreated: Date()
// ),
// .init(
//    title: "Dairy",
//    description: "Milk/lactose",
//    icon: "cup.and.saucer.fill",
//    color: 0x008DC6,
//    words: [
//        "Milk",
//        "Butter",
//        "Casein",
//        "Cheese",
//        "Cream",
//        "Custard",
//        "Whey",
//        "Lactalbumin",
//        "Lactoglobulin",
//        "Lactoferrin",
//        "Lactose",
//        "Margarine",
//        "Nisin",
//        "Nougat",
//        "Rennet",
//        "Yogurt"
//    ],
//    dateCreated: Date()
// ),
// .init(
//    title: "Gluten",
//    description: "Wheat and other stuff",
//    icon: "cup.and.saucer.fill",
//    color: 0xFFA701,
//    words: [
//        "Gluten",
//        "Wheat",
//        "Barley",
//        "Bulgur",
//        "Couscous",
//        "Durum",
//        "Einkorn",
//        "Emmer",
//        "Farina",
//        "Farro",
//        "Graham flour",
//        "Kamut",
//        "Matzo",
//        "Orzo",
//        "Panko",
//        "Rye",
//        "Seitan",
//        "Semolina",
//        "Spelt",
//        "Triticale",
//        "Udon"
//    ],
//    dateCreated: Date()
// ),
// .init(
//    title: "Eggs",
//    description: "Eggs, eggs, eggs",
//    icon: "oval.portrait",
//    color: 0xF3FD8F,
//    words: [
//        "Egg",
//        "Albumin",
//        "Apovitellin",
//        "Globulin",
//        "Livetin",
//        "Lysozyme",
//        "Ovalbumin",
//        "Ovoglobulin",
//        "Ovomucin",
//        "Ovomucoid",
//        "Ovotransferrin",
//        "Ovovitellin",
//        "Silici albuminate",
//        "Simplesse",
//        "Vitellin"
//    ],
//    dateCreated: Date()
// ),
// .init(
//    title: "Soy",
//    description: "Soy products",
//    icon: "square.fill",
//    color: 0xA20066,
//    words: [
//        "Soy",
//        "Edamame",
//        "Miso",
//        "Natto",
//        "Tamari",
//        "Tempeh",
//        "Teriyaki sauce",
//        "TVP",
//        "Tofu",
//        "Soy",
//        "Edamame",
//        "Miso",
//        "Natto",
//        "Tamari",
//        "Tempeh"
//    ],
//    dateCreated: Date()
// ),
// .init(
//    title: "Kosher Restrictions",
//    description: "Common Foods",
//    icon: "checkmark",
//    color: 0x3A7921,
//    words: [
//        "Pork",
//        "Gelatin",
//        "Shrimp",
//        "Lobster",
//        "Crab",
//        "Clam",
//        "Oyster",
//        "Sirloin",
//        "Flank",
//        "Shank"
//    ],
//    dateCreated: Date()
// ),
// .init(
//    title: "Halal Restrictions",
//    description: "Common Foods",
//    icon: "checkmark",
//    color: 0x009A00,
//    words: [
//        "Pork",
//        "Gelatin"
//    ],
//    dateCreated: Date()
// )
