//
//  PopulateSymbols.swift
//  Find
//
//  Created by Zheng on 2/12/20.
//  Copyright © 2020 Andrew. All rights reserved.
//

import Foundation

extension SymbolsViewController {
    
    func populateSymbols() {
        techList = ["square.grid.2x2", "pencil", "pencil.circle", "pencil.slash", "square.and.pencil", "pencil.and.ellipsis.rectangle", "pencil.and.outline", "trash", "trash.circle", "trash.slash", "folder", "folder.circle", "folder.badge.plus", "folder.badge.minus", "folder.badge.person.crop", "paperplane", "tray", "tray.and.arrow.up", "tray.and.arrow.down", "tray.2", "tray.full", "archivebox", "bin.xmark", "arrow.up.bin", "calendar", "calendar.circle", "calendar.badge.plus", "calendar.badge.minus", "book", "book.circle", "bookmark", "rosette", "paperclip", "paperclip.circle", "rectangle.and.paperclip", "link", "link.circle", "pencil.tip", "pencil.tip.crop.circle", "pencil.tip.crop.circle.badge.plus", "pencil.tip.crop.circle.badge.minus", "umbrella", "speaker", "speaker.slash", "speaker.zzz", "speaker.1", "speaker.2", "speaker.3", "magnifyingglass", "magnifyingglass.circle", "plus.magnifyingglass", "minus.magnifyingglass", "1.magnifyingglass", "flag", "flag.circle", "flag.slash", "bell", "bell.circle", "bell.slash", "tag", "tag.circle", "camera", "camera.circle", "camera.rotate", "camera.on.rectangle", "gear", "scissors", "scissors.badge.ellipsis", "wand.and.rays", "wand.and.rays.inverse", "wand.and.stars", "wand.and.stars.inverse", "crop", "crop.rotate", "dial", "gauge", "gauge.badge.plus", "gauge.badge.minus", "speedometer", "metronome", "tuningfork", "paintbrush", "bandage", "wrench", "hammer", "eyedropper", "eyedropper.halffull", "eyedropper.full", "printer", "briefcase", "lock", "lock.circle", "lock.slash", "lock.open", "lock.rotation", "lock.rotation.open", "pin", "pin.circle", "pin.slash", "mappin", "mappin.circle", "mappin.slash", "mappin.and.ellipse", "map", "antenna.radiowaves.left.and.right", "guitars", "bed.double", "film", "camera.viewfinder", "shield", "shield.slash", "lock.shield", "checkmark.shield", "xmark.shield", "exclamationmark.shield", "cube.box", "clock", "alarm", "stopwatch", "timer", "gamecontroller", "headphones", "gift", "hourglass", "perspective", "aspectratio", "skew", "eyeglasses", "lightbulb", "lightbulb.slash", "keyboard", "keyboard.chevron.compact.down", "hifispeaker", "printer", "tv", "tv.circle", "tv.music.note", "desktopcomputer", "gamecontroller", "headphones", "car", "airplane"]
        
        weatherList = ["sun.min", "sun.max", "sunrise", "sunset", "sun.dust", "sun.haze", "moon", "moon.circle", "zzz", "moon.zzz", "sparkles", "moon.stars", "cloud", "cloud.drizzle", "cloud.rain", "cloud.heavyrain", "cloud.fog", "cloud.hail", "cloud.snow", "cloud.sleet", "cloud.bolt", "cloud.sun", "cloud.sun.rain", "cloud.sun.bolt", "cloud.moon", "cloud.moon.rain", "cloud.bolt.rain", "cloud.moon.bolt", "smoke", "wind", "snow", "wind.snow", "tornado", "tropicalstorm", "hurricane", "thermometer.sun", "thermometer.snowflake", "thermometer"]

        
        natureAndHealthList = ["flame", "bolt", "bolt.circle", "bolt.slash", "ant", "ant.circle", "hare", "tortoise", "leaf.arrow.circlepath", "heart", "heart.circle", "bandage", "bed.double", "waveform.path.ecg", "staroflife"]

        
        numbersList = ["00.circle", "01.circle", "02.circle", "03.circle", "04.circle", "05.circle", "06.circle", "07.circle", "08.circle", "09.circle", "0.circle", "1.circle", "2.circle", "3.circle", "4.circle", "5.circle", "6.circle", "7.circle", "8.circle", "9.circle", "10.circle", "11.circle", "12.circle", "13.circle", "14.circle", "15.circle", "16.circle", "17.circle", "18.circle", "19.circle", "20.circle", "21.circle", "22.circle", "23.circle", "24.circle", "25.circle", "26.circle", "27.circle", "28.circle", "29.circle", "30.circle", "31.circle", "32.circle", "33.circle", "34.circle", "35.circle", "36.circle", "37.circle", "38.circle", "39.circle",  "40.circle", "41.circle", "42.circle", "43.circle", "44.circle", "45.circle", "46.circle", "47.circle", "48.circle", "49.circle", "50.circle", "00.square", "01.square", "02.square", "03.square", "04.square", "05.square", "06.square", "07.square", "08.square", "09.square", "0.square", "1.square", "2.square", "3.square", "4.square", "5.square", "6.square", "7.square", "8.square", "9.square", "10.square", "11.square", "12.square", "13.square", "14.square", "15.square", "16.square", "17.square", "18.square", "19.square", "20.square", "21.square", "22.square", "23.square", "24.square", "25.square", "26.square", "27.square", "28.square", "29.square", "30.square", "31.square", "32.square", "33.square", "34.square", "35.square", "36.square", "37.square", "38.square", "39.square", "40.square", "41.square", "42.square", "43.square", "44.square", "45.square", "46.square", "47.square", "48.square", "49.square", "50.square"]
        
        mathList = ["rectangle", "shield", "hexagon", "app", "triangle", "capsule", "circle", "square", "sum", "percent", "function", "plus", "plus.circle", "plus.square", "minus", "minus.circle", "minus.square", "plusminus", "plusminus.circle", "plus.slash.minus", "minus.slash.plus", "multiply", "multiply.circle", "multiply.square", "divide", "divide.circle", "divide.square", "equal", "equal.circle", "equal.square", "lessthan", "lessthan.circle", "lessthan.square", "greaterthan", "greaterthan.circle", "greaterthan.square", "number", "number.circle", "number.square", "x.squareroot"]
        
        currencyList = ["signature", "bag", "bag.badge.plus", "bag.badge.minus", "cart", "cart.badge.plus", "cart.badge.minus", "creditcard", "dollarsign.circle", "centsign.circle", "yensign.circle", "sterlingsign.circle", "francsign.circle", "florinsign.circle", "turkishlirasign.circle", "rublesign.circle", "eurosign.circle", "dongsign.circle", "indianrupeesign.circle", "tengesign.circle", "pesetasign.circle", "pesosign.circle", "kipsign.circle", "wonsign.circle", "lirasign.circle", "australsign.circle", "hryvniasign.circle", "nairasign.circle", "guaranisign.circle", "coloncurrencysign.circle", "cedisign.circle", "cruzeirosign.circle", "tugriksign.circle", "millsign.circle", "sheqelsign.circle", "manatsign.circle", "rupeesign.circle", "bahtsign.circle", "larisign.circle", "bitcoinsign.circle", "dollarsign.square", "cedisign.square", "cruzeirosign.square", "tugriksign.square", "millsign.square", "sheqelsign.square", "manatsign.square", "rupeesign.square", "bahtsign.square", "larisign.square", "bitcoinsign.square"]

        
         speechList = ["mic", "mic.circle", "mic.slash", "message", "message.circle", "bubble.right", "bubble.left", "exclamationmark.bubble", "quote.bubble", "t.bubble", "text.bubble", "captions.bubble", "plus.bubble", "ellipses.bubble", "bubble.left.and.bubble.right", "phone", "phone.circle", "phone.badge.plus", "phone.arrow.up.right", "phone.arrow.down.left", "phone.arrow.right", "phone.down", "phone.down.circle", "teletype", "teletype.answer", "video", "video.circle", "video.slash", "video.badge.plus", "arrow.up.right.video", "arrow.down.left.video", "questionmark.video", "envelope", "envelope.circle", "envelope.open", "envelope.badge"]

    }
}
